# Generated by Django 3.2.15 on 2023-07-31 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='排序数字')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='菜单访问的url')),
                ('delete_flag', models.CharField(default='o', max_length=1, verbose_name='标记删除')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名字')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_systems.menumodel')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 't_menu',
            },
        ),
    ]
